# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: 'teste.com'
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Deploy dev

  deploy-hmg:
    runs-on: ubuntu-latest
    environment:
      name: hmg
      url: 'teste.com'
    needs: deploy-dev
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Deploy hmg
        
  deploy-prd:
    runs-on: ubuntu-latest
    environment:
      name: prd
      url: 'teste.com'
    needs: deploy-hmg
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Deploy prd
